# Generated by Django 5.2.5 on 2025-09-11 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('place_type', models.CharField(choices=[('accomodation', 'Hostel/PG/Room'), ('hotel', 'Hotel'), ('mess', 'Mess'), ('bakery', 'Bakery'), ('stall', 'Food Stall'), ('stationery', 'Stationery'), ('grocery', 'Grocery')], default='accomodation', max_length=20)),
                ('price_tier', models.CharField(choices=[('economy', 'Economical'), ('average', 'Average'), ('premium', 'Premium')], default='economy', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
        ),
    ]
